server:
    port: 8080

spring:
    datasource:
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://localhost:3306/ottDB"
        username: "root"
        password: "qwer1234"
        connectionProperties: serverTimezone=UTC;useSSL=false;useUnicode=true;characterEncoding=UTF-8

    mvc:
        view:
            prefix: /WEB-INF/views
            suffix: .jsp

mybatis:
    mapper-locations: classpath:com/cm/ott/dao/*.xml